bundler_args: ""
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
gemfile:
 - gemfiles/rails2.gemfile
 - gemfiles/rails3.gemfile
 - gemfiles/rails40.gemfile
 - gemfiles/rails41.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails2.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/rails2.gemfile
script: bundle exec rake spec
