bundler_args: ""
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
 - gemfiles/rails2.gemfile
 - gemfiles/rails3.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails2.gemfile
script: bundle exec rake spec
